#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

# Get the list of staged files
# staged_files=$(git diff --cached --name-only -- 'src/*.tsx' 'src/*.ts')

git stash --keep-index -u

# Run ESLint on staged files
npm run lint --quiet

# Check ESLint exit status
eslint_exit_status=$?

git stash pop

# Exit with the ESLint exit status
exit $eslint_exit_status