#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the list of staged files
staged_files=$(git diff --cached --name-only -- 'src/*.tsx' 'src/*.ts')

git stash --keep-index

# Run ESLint on staged files
npx eslint $staged_files --fix

# Check ESLint exit status
eslint_exit_status=$?

# Pop stashed changes only if ESLint ran successfully
if [ $eslint_exit_status -eq 0 ]; then
  echo "ESLint success"
else
  echo "ESLint found errors. Stashed changes were not popped."
fi


git stash pop 

# Exit with the ESLint exit status
exit $eslint_exit_status